import { sva } from "#styled-system/css";

export const alertDialogRecipe = sva({
  slots: [
    "root",
    "overlay",
    "content",
    "title",
    "description",
    "header",
    "footer",
    "body",
    "cancel",
  ],
  base: {
    root: {
      display: "flex",
      w: "full",
    },
    overlay: {
      pos: "fixed",
      top: "0",
      left: "0",
      w: "full",
      h: "full",
      bg: "white",
      opacity: 0.5,
      backdropBlur: "xl",
    },
    content: {
      pos: "fixed",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      w: { mdDown: "4/5", md: "md" },
      bg: "surface.muted",
      borderWidth: "1",
      borderColor: "surface.border",
      px: "4",
      py: "4",
      rounded: "radius",
    },
    header: {
      pos: "relative",
      w: "full",
      alignItems: "stretch",
      display: "flex",
      flexDir: "column",
      px: "4",
      py: "4",
    },
    body: {
      w: "full",
      flex: "1",
      display: "flex",
      flexDir: "column",
      alignItems: "stretch",
      px: "4",
      py: "4",
    },
    footer: {
      w: "full",
      display: "flex",
      flexDir: "row",
      gap: "4",
      alignItems: "center",
      justifyContent: "flex-end",
      px: "4",
      py: "4",
    },
  },
});
